substitutions:
  # names
  name: "fluval-hub"
  friendly_name: "Fluval Hub"
  # App Version - Updated: 6/2024
  app_version: "2024.7.0"

packages:
  device_base: !include common/device_base.yaml
  fluval_marine: !include common/fluval_bluetooth_marine.yaml

web_server: !remove