substitutions:
  # names
  name: "fluval-hub"
  friendly_name: "Fluval Hub"
  app_version: "24.11.0"

packages:
  device_base: !include common/device_base.yaml
  # fluval_marine: !include common/fluval_bluetooth_marine.yaml
  # fluval_planted: !include common/fluval_bluetooth_planted.yaml
  # debug: !include common/debug.yaml
  # dht: !include common/dht.yaml

# web_server: !remove
