substitutions:
  comment: "Fluval Bluetooth Hub"
  logger: "DEBUG"
  
  # I2C pins
  sdaPin: "21" # blue
  sclPin: "22" # yellow

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  # Automatically add the mac address to the name
  name_add_mac_suffix: true
  comment: "${comment}"
  project:
    name: therealfalsereality.fluval-bluetooth-hub
    version: "${app_version}"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: "${logger}"

api:

ota:
  platform: esphome

wifi: 
  ap:

captive_portal:

# web_server:

esp32_ble_tracker:

time:
  - platform: homeassistant
    id: ha_time

external_components:
  - source: github://mrzottel/esphome@fluval_ble_led
    components: [ fluval_ble_led ]

# # Sets up Bluetooth LE (Only on ESP32) to allow the user to provision wifi credentials to the device.
esp32_improv:
  authorizer: none
  
improv_serial:

# i2c Pins
i2c:
  sda: ${sdaPin}
  scl: ${sclPin}
  scan: true
  id: bus_a

# Internal Blue LED
light:
  - platform: status_led
    id: internal_led
    pin:
      number: GPIO2
      ignore_strapping_warning: true

sensor:
  # Internal Magnetic Sensor
  - platform: esp32_hall
    name: "ESP32 Hall Sensor"
    entity_category: "diagnostic"

  # Internal Temp.
  - platform: internal_temperature
    name: "Internal Temperature"

  # Wifi Signal 
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    # name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  # Wifi %
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

    # Uptime sensor
  - platform: uptime
    name: Uptime 

binary_sensor:
  # API Status
  - platform: status
    name: "Status"

text_sensor: 
  # Hostname
  - platform: template
    name: "Hostname"
    id: hostname
    icon: mdi:cellphone-arrow-down
    lambda: |-
      return {"${name}"};
    entity_category: "diagnostic"

  # Wifi Info
  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip-network
    ssid:
      name: Connected SSID
      icon: mdi:wifi-arrow-left-right
    bssid:
      name: Connected BSSID
      icon: mdi:wifi-star
      disabled_by_default: true
    mac_address:
      name: Mac Address
      icon: mdi:chip

  # Version
  - platform: template
    name: "Version"
    id: app_version
    icon: mdi:update
    update_interval: 600s
    lambda: |-
      return {"${app_version}"};
    entity_category: "diagnostic"

button:
  # Soft Restart
  - platform: restart
    id: restart_button
    name: "Restart"

  # Factory Reset
  - platform: factory_reset
    name: Factory Reset (USE WITH CAUTION)
    disabled_by_default: true

  # Safe Mode Restart
  - platform: safe_mode
    name: "Restart in Safe Mode"
    id: restart_safe

  # Shutdown
  - platform: shutdown
    name: "Shutdown"
    disabled_by_default: true
    id: shutdown_button