substitutions:
  mac_address_marine: '00:00:00:00:00:00'

ble_client:
  - mac_address: ${mac_address_marine}
    id: ble_fluval_marine

fluval_ble_led:
  - ble_client_id: ble_fluval_marine
    time_id: ha_time
    number_of_channels: 5
    id: fluval_marine

sensor:
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    channel: 1
    zero_if_off: true
    name: "Marine - Pink"

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    channel: 2
    zero_if_off: true
    name: "Marine - Cyan"

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    channel: 3
    zero_if_off: true
    name: "Marine - Blue"

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    channel: 4
    zero_if_off: true
    name: "Marine - Purple"

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    channel: 5
    zero_if_off: true
    name: "Marine - Cold White"

button:    
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    mode: "MANUAL"
    name: "Marine - Switch to Manual"
    icon: mdi:lightbulb-alert

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    mode: "AUTO"
    name: "Marine - Switch to Auto"
    icon: mdi:lightbulb-auto-outline

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    mode: "PRO"
    name: "Marine - Switch to Pro"
    icon: mdi:lightbulb-on

switch:
  - platform: ble_client
    ble_client_id: ble_fluval_marine
    name: "Marine Bluetooth Connection"
    restore_mode: RESTORE_DEFAULT_ON

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    name: "Marine Fluval Light"
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:led-strip

text_sensor:
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    mapping_manual: "Manual"
    mapping_auto: "Auto"
    mapping_pro: "Pro"
    name: "Marine Fluval Light Mode"
    icon: mdi:lightbulb-group

number:
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    name: "Marine - Pink"
    channel: 1
    zero_if_off: true

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    name: "Marine - Cyan"
    channel: 2
    zero_if_off: true

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    name: "Marine - Blue"
    channel: 3
    zero_if_off: true

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    name: "Marine - Purple"
    channel: 4
    zero_if_off: true

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_marine
    name: "Marine - Cold White"
    channel: 5
    # max_value: 500
    # min_value: 200
    # step: 50
    zero_if_off: true