substitutions:
  mac_address_planted: '00:00:00:00:00:00'

ble_client:
  - mac_address: ${mac_address_planted}
    id: ble_fluval_planted

fluval_ble_led:
  - ble_client_id: ble_fluval_planted
    time_id: ha_time
    number_of_channels: 5
    id: fluval_planted

sensor:
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 1
    zero_if_off: true
    name: "Planted - Pink"

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 2
    zero_if_off: true
    name: "Planted - Blue"

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 3
    zero_if_off: true
    name: "Planted - Cold White"

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 4
    zero_if_off: true
    name: "Planted - Pure White"

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 5
    zero_if_off: true
    name: "Planted - Warm White"

button:    
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    mode: "MANUAL"
    name: "Planted - Switch to Manual"

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    mode: "AUTO"
    name: "Planted - Switch to Auto"

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    mode: "PRO"
    name: "Planted - Switch to Pro"

switch:
  - platform: ble_client
    ble_client_id: ble_fluval_planted
    name: "Planted Bluetooth Connection"
    restore_mode: RESTORE_DEFAULT_ON

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted Fluval Light"

text_sensor:
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    mapping_manual: "Manual"
    mapping_auto: "Auto"
    mapping_pro: "Pro"
    name: "Planted Fluval Light Mode"

number:
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Pink"
    channel: 1
    zero_if_off: true

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Blue"
    channel: 2
    zero_if_off: true

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Cold White"
    channel: 3
    zero_if_off: true

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Pure White"
    channel: 4
    zero_if_off: true

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Warm White"
    channel: 5
    # max_value: 500
    # min_value: 200
    # step: 50
    zero_if_off: true