substitutions:
  mac_address_planted: '00:00:00:00:00:00'

ble_client:
  - mac_address: ${mac_address_planted}
    id: ble_fluval_planted

fluval_ble_led:
  - ble_client_id: ble_fluval_planted
    time_id: ha_time
    number_of_channels: 5
    id: fluval_planted

sensor:
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 1
    zero_if_off: true
    name: "Planted - Pink"
    id: planted_pink
    disabled_by_default: true

  - platform: copy
    name: Planted - Pink Brightness
    source_id: planted_pink
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
         method: least_squares
         datapoints:
          - 0.0 -> 0.0
          - 1000.0 -> 100.0

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 2
    zero_if_off: true
    name: "Planted - Blue"
    id: planted_blue
    disabled_by_default: true

  - platform: copy
    name: Planted - Blue Brightness
    source_id: planted_blue
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
         method: least_squares
         datapoints:
          - 0.0 -> 0.0
          - 1000.0 -> 100.0

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 3
    zero_if_off: true
    name: "Planted - Cold White"
    id: planted_cold_white
    disabled_by_default: true

  - platform: copy
    name: Planted - Cold White Brightness
    source_id: planted_cold_white
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
         method: least_squares
         datapoints:
          - 0.0 -> 0.0
          - 1000.0 -> 100.0

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 4
    zero_if_off: true
    name: "Planted - Pure White"
    id: planted_pure_white
    disabled_by_default: true

  - platform: copy
    name: Planted - Pure White Brightness
    source_id: planted_pure_white
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
         method: least_squares
         datapoints:
          - 0.0 -> 0.0
          - 1000.0 -> 100.0

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 5
    zero_if_off: true
    name: "Planted - Warm White"
    id: planted_warm_white
    disabled_by_default: true

  - platform: copy
    name: Planted - Warm White Brightness
    source_id: planted_warm_white
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
         method: least_squares
         datapoints:
          - 0.0 -> 0.0
          - 1000.0 -> 100.0

button:    
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    mode: "MANUAL"
    name: "Planted - Switch to Manual"
    icon: mdi:lightbulb-alert

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    mode: "AUTO"
    name: "Planted - Switch to Auto"
    icon: mdi:lightbulb-auto

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    mode: "PRO"
    name: "Planted - Switch to Pro"
    icon: mdi:lightbulb-on

switch:
  - platform: ble_client
    ble_client_id: ble_fluval_planted
    name: "Planted Bluetooth Connection"
    restore_mode: RESTORE_DEFAULT_ON

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted Fluval Light"
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:flower

text_sensor:
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    mapping_manual: "Manual"
    mapping_auto: "Auto"
    mapping_pro: "Pro"
    name: "Planted Fluval Light Mode"
    icon: mdi:lightbulb-group

number:
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Pink"
    channel: 1
    zero_if_off: true

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Blue"
    channel: 2
    zero_if_off: true

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Cold White"
    channel: 3
    zero_if_off: true

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Pure White"
    channel: 4
    zero_if_off: true

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Warm White"
    channel: 5
    # max_value: 500
    # min_value: 200
    # step: 50
    zero_if_off: true