substitutions:
  mac_address_planted: '00:00:00:00:00:00'

ble_client:
  - mac_address: ${mac_address_planted}
    id: ble_fluval_planted

esp32_ble_tracker:
  on_ble_advertise:
    - mac_address:
        - ${mac_address_planted}
      then:
        - lambda: |-
            ESP_LOGD("ble_adv", "New BLE device");
            ESP_LOGD("ble_adv", "  address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  name: %s", x.get_name().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
                ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
            ESP_LOGD("ble_adv", "  Advertised service data:");
            for (auto data : x.get_service_datas()) {
                ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
            }
            ESP_LOGD("ble_adv", "  Advertised manufacturer data:");
            for (auto data : x.get_manufacturer_datas()) {
                ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
            }

fluval_ble_led:
  - ble_client_id: ble_fluval_planted
    time_id: ha_time
    number_of_channels: 5
    id: fluval_planted

sensor:
  - platform: ble_rssi
    mac_address: ${mac_address_planted}
    name: Planted Fluval Light Signal
    id: bluetooth_signal_planted
    disabled_by_default: True
    entity_category: "diagnostic"

  - platform: copy
    source_id: bluetooth_signal_planted
    name: Planted Fluval Light Signal Strength
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 1
    zero_if_off: true
    name: "Planted - Pink"
    id: fluval_planted_pink
    disabled_by_default: true

  - platform: copy
    name: Planted - Pink Brightness
    source_id: fluval_planted_pink
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
         method: least_squares
         datapoints:
          - 0.0 -> 0.0
          - 1000.0 -> 100.0

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 2
    zero_if_off: true
    name: "Planted - Blue"
    id: fluval_planted_blue
    disabled_by_default: true

  - platform: copy
    name: Planted - Blue Brightness
    source_id: fluval_planted_blue
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
         method: least_squares
         datapoints:
          - 0.0 -> 0.0
          - 1000.0 -> 100.0

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 3
    zero_if_off: true
    name: "Planted - Cold White"
    id: fluval_planted_cold_white
    disabled_by_default: true

  - platform: copy
    name: Planted - Cold White Brightness
    source_id: fluval_planted_cold_white
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
         method: least_squares
         datapoints:
          - 0.0 -> 0.0
          - 1000.0 -> 100.0

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 4
    zero_if_off: true
    name: "Planted - Pure White"
    id: fluval_planted_pure_white
    disabled_by_default: true

  - platform: copy
    name: Planted - Pure White Brightness
    source_id: fluval_planted_pure_white
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
         method: least_squares
         datapoints:
          - 0.0 -> 0.0
          - 1000.0 -> 100.0

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    channel: 5
    zero_if_off: true
    name: "Planted - Warm White"
    id: fluval_planted_warm_white
    disabled_by_default: true

  - platform: copy
    name: Planted - Warm White Brightness
    source_id: fluval_planted_warm_white
    unit_of_measurement: '%'
    filters:
      - calibrate_linear:
         method: least_squares
         datapoints:
          - 0.0 -> 0.0
          - 1000.0 -> 100.0

button:    
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    mode: "MANUAL"
    name: "Planted - Switch to Manual"
    icon: mdi:lightbulb-alert

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    mode: "AUTO"
    name: "Planted - Switch to Auto"
    icon: mdi:lightbulb-auto

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    mode: "PRO"
    name: "Planted - Switch to Pro"
    icon: mdi:lightbulb-on

switch:
  - platform: ble_client
    ble_client_id: ble_fluval_planted
    name: "Planted Bluetooth Connection"
    restore_mode: RESTORE_DEFAULT_ON

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted Fluval Light"
    restore_mode: RESTORE_DEFAULT_ON
    icon: mdi:flower

text_sensor:
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    mapping_manual: "Manual"
    mapping_auto: "Auto"
    mapping_pro: "Pro"
    name: "Planted Fluval Light Mode"
    icon: mdi:lightbulb-group

number:
  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Pink"
    channel: 1
    zero_if_off: true
    step: 10

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Blue"
    channel: 2
    zero_if_off: true
    step: 10

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Cold White"
    channel: 3
    zero_if_off: true
    step: 10

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Pure White"
    channel: 4
    zero_if_off: true
    step: 10

  - platform: fluval_ble_led
    fluval_ble_led_id: fluval_planted
    name: "Planted - Warm White"
    channel: 5
    zero_if_off: true
    step: 10